update jenkinsfile

diff --git a/lab2/Jenkinsfile b/lab2/Jenkinsfile
--- a/lab2/Jenkinsfile
+++ b/lab2/Jenkinsfile
@@ -36,7 +36,24 @@ pipeline {
        
 
                     echo 'Dependency installation'
-                    sh 'pip install -r lab2/requirements.txt'
+                    sh '''
+                        if [ ! -f "lab2/requirements.txt" ]; then
+                            echo "File requirements.txt not found."
+                            return 1
+                        fi
+
+                        # Check if all dependencies from requirements.txt are installed
+                        for package in $(cat lab2/requirements.txt | cut -d '=' -f 1); do
+                            if ! pip freeze | grep -q "^$package=="; then
+                                echo "Dependency installation..."
+                                pip install -r lab2/requirements.txt
+                                echo "Dependencies installed."
+                                return 0
+                            fi
+                        done
+
+                        echo "All dependencies are already installed."
+                    '''
                     
                 }                
             }
